[package]
name = "zestors-client-api"
version = "0.1.0"
edition = "2024"

[dependencies]
zestors.workspace = true
rootcause = { workspace = true, features = ["compat-anyhow1"] }

anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
oas3-gen-support = "0.27"
validator = { version = "0.21", features = ["derive"] }
reqwest = { workspace = true, features = ["json"] }
http = { version = "1" }
