[package]
name = "zestors"
version = "0.1.0"
edition = "2024"

[dependencies]
futures.workspace = true
tracing.workspace = true
rootcause.workspace = true
zestors-core.workspace = true
zestors-api-server.workspace = true

[dev-dependencies]
tracing-subscriber.workspace = true
tokio.workspace = true
serde.workspace = true

[features]
_ra = []
