[package]
name = "zestors"
version = "0.1.0"
edition = "2024"

[dependencies]
polybox-codegen.workspace = true
tokio.workspace = true
futures.workspace = true
tracing.workspace = true
rootcause.workspace = true
thiserror.workspace = true
indexmap.workspace = true
async-channel.workspace = true
smol_str.workspace = true
type-sets.workspace = true
serde.workspace = true
dashmap.workspace = true
arc-swap.workspace = true
rand.workspace = true
bs58.workspace = true
axum.workspace = true
serde_json.workspace = true
utoipa-axum.workspace = true
# utoipa-swagger-ui.workspace = true
utoipa.workspace = true
axum-autoroute.workspace = true
concurrent-queue.workspace = true
eyeball.workspace = true
zestors-core.workspace = true

[dev-dependencies]
tracing-subscriber.workspace = true

[features]
_ra = []
