[package]
name = "zestors"
version = "0.1.0"
edition = "2024"

[dependencies]
# polybox.workspace = true
polybox-codegen.workspace = true
tokio.workspace = true
futures.workspace = true
tracing.workspace = true
anyhow.workspace = true
thiserror.workspace = true
indexmap.workspace = true
async-channel.workspace = true
smol_str.workspace = true
type-sets.workspace = true
serde.workspace = true
dashmap.workspace = true
uuid.workspace = true

[features]
_ra = []
