/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ActorStatus {
    #[serde(rename = "Running")]
    Running,
    #[serde(rename = "Suspended")]
    Suspended,
    #[serde(rename = "ShuttingDown")]
    ShuttingDown,

}

impl std::fmt::Display for ActorStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Running => write!(f, "Running"),
            Self::Suspended => write!(f, "Suspended"),
            Self::ShuttingDown => write!(f, "ShuttingDown"),
        }
    }
}

impl Default for ActorStatus {
    fn default() -> ActorStatus {
        Self::Running
    }
}

