/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DebugState {
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "status")]
    pub status: models::ActorStatus,
    #[serde(rename = "uptime")]
    pub uptime: Box<models::DurationSchema>,
}

impl DebugState {
    pub fn new(description: String, status: models::ActorStatus, uptime: models::DurationSchema) -> DebugState {
        DebugState {
            description,
            status,
            uptime: Box::new(uptime),
        }
    }
}

