/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DurationSchema {
    #[serde(rename = "nanos")]
    pub nanos: i32,
    #[serde(rename = "secs")]
    pub secs: i64,
}

impl DurationSchema {
    pub fn new(nanos: i32, secs: i64) -> DurationSchema {
        DurationSchema {
            nanos,
            secs,
        }
    }
}

