/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RestartMode {
    #[serde(rename = "Always")]
    Always,
    #[serde(rename = "OnError")]
    OnError,
    #[serde(rename = "Never")]
    Never,

}

impl std::fmt::Display for RestartMode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Always => write!(f, "Always"),
            Self::OnError => write!(f, "OnError"),
            Self::Never => write!(f, "Never"),
        }
    }
}

impl Default for RestartMode {
    fn default() -> RestartMode {
        Self::Always
    }
}

