/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SupervisionTree {
    #[serde(rename = "abort_timeout")]
    pub abort_timeout: String,
    #[serde(rename = "children", skip_serializing_if = "Option::is_none")]
    pub children: Option<Vec<models::SupervisionTree>>,
    #[serde(rename = "debug_state", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub debug_state: Option<Option<Box<models::DebugState>>>,
    #[serde(rename = "pid")]
    pub pid: String,
    #[serde(rename = "restart_mode")]
    pub restart_mode: models::RestartMode,
}

impl SupervisionTree {
    pub fn new(abort_timeout: String, pid: String, restart_mode: models::RestartMode) -> SupervisionTree {
        SupervisionTree {
            abort_timeout,
            children: None,
            debug_state: None,
            pid,
            restart_mode,
        }
    }
}

